### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by jordynojeda**
Python is misspelled.

### CODE REVIEW

**Comment by jordynojeda** [comment]
Done.

**Comment by zijin-gu** [comment]
Good catch! Thanks!

**Comment by jordynojeda** [comment]
Your welcome!

**Comment by jordynojeda** [comment]
Hello, 

I am trying to run the code for your model. I am having trouble gathering the required packages to run your model. Could you please provide me with a list of packages. I could not find them in the repository link here: https://github.com/zijin-gu/meshconv-decoding 

Thank you

**Comment by zijin-gu** [comment]
Hi,

I have updated the readme file. Besides the commonly used packages, you will need to clone the IC-GAN repo first.

**Comment by jordynojeda** [comment]
Thank you so much!

**Comment by jordynojeda** [comment]
Thank you for updating the requirements. Could you please send over all the .npy files referenced in the dataloader.py file? We have a copy of NSD but, will need the files not within NSD or the method you used to generate them. 

I am working on a similar project in Thomas Naselaris lab at the University of Minnesota and would like to build upon your research.

Jordyn Ojeda 
BS Computer Science
***@***.*** <> 
651-600-0046

**Comment by zijin-gu** [comment]
Hi Jordyn,

Thank you for your interest. 

Unfortunately I don’t think I am allowed to directly share the npy files. But since you have access to NSD, you should able to generate the files yourself.
For MRI files you can use the new file I uploaded map_fsaverage_to_hcp.sh to map your data onto 32K surface.

Best,
Zijin Gu

**Pull request closed without merging**
